import { cp, mkdir, readFile, access } from 'node:fs/promises';
import { resolve } from 'node:path';
import { projects } from '../public/projects.js';
import { toolGroups } from '../public/tools.js';
const root=resolve(import.meta.dirname,'..');
const html=await readFile(resolve(root,'public/index.html'),'utf8');
for(const match of html.matchAll(/(?:src|href)="(\/[^"#?]+)"/g))await access(resolve(root,'public',match[1].slice(1)));
for(const p of projects)if(p.image)await access(resolve(root,`public/assets/${p.image}`));
for(const group of toolGroups)for(const [,icon] of group.tools)await access(resolve(root,`public/assets/tools/${icon}.svg`));
await mkdir(resolve(root,'dist'),{recursive:true});
await cp(resolve(root,'public'),resolve(root,'dist'),{recursive:true});
console.log(`Built ${projects.length} case studies and verified local assets. Server functions remain in api/.`);
